name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build backend
      run: ./gradlew build

    - name: Build frontend
      run: |
        cd frontEnd-dev
        npm install
        npm run build

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: 18.223.155.159
        USER: ec2-user
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        scp -o StrictHostKeyChecking=no -i private_key.pem -r frontEnd-dev/build/* $USER@$HOST:/usr/share/nginx/html/
        scp -o StrictHostKeyChecking=no -i private_key.pem build/libs/final-0.0.1-SNAPSHOT.jar $USER@$HOST:~/backEnd-dev/
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "java -jar ~/backEnd-dev/final-0.0.1-SNAPSHOT.jar --server.port=8080 &"
